<!DOCTYPE report [
        <!ELEMENT report (report|report_format|sort|filters|scan_run_status|task|scan_start|ports|results|result_count|host|host_start|host_end|scan_end)*>
        <!ATTLIST report
                content_type CDATA #IMPLIED
                extension CDATA #IMPLIED
                format_id CDATA #IMPLIED
                id CDATA #REQUIRED
                type CDATA #IMPLIED>
        <!ELEMENT report_format (#PCDATA)>
        <!ELEMENT sort (field)*>
        <!ELEMENT field (order)*>
        <!ELEMENT order (#PCDATA)>
        <!ELEMENT filters (term|phrase|autofp|show_closed_cves|notes|overrides|apply_overrides|result_hosts_only|min_cvss_base|filter)*>
        <!ATTLIST filters
                id CDATA #REQUIRED>
        <!ELEMENT term (#PCDATA)>
        <!ELEMENT phrase (#PCDATA)>
        <!ELEMENT autofp (#PCDATA)>
        <!ELEMENT show_closed_cves (#PCDATA)>
        <!ELEMENT notes (#PCDATA)>
        <!ELEMENT overrides (#PCDATA)>
        <!ELEMENT apply_overrides (#PCDATA)>
        <!ELEMENT result_hosts_only (#PCDATA)>
        <!ELEMENT min_cvss_base (#PCDATA)>
        <!ELEMENT filter (#PCDATA)>
        <!ELEMENT scan_run_status (#PCDATA)>
        <!ELEMENT task (name|comment|target)*>
        <!ATTLIST task
                id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT comment (#PCDATA)>
        <!ELEMENT target (trash)*>
        <!ATTLIST target
                id CDATA #REQUIRED>
        <!ELEMENT trash (#PCDATA)>
        <!ELEMENT scan_start (#PCDATA)>
        <!ELEMENT ports (port)*>
        <!ATTLIST ports
                start CDATA #REQUIRED
                max CDATA #REQUIRED>
        <!ELEMENT port (host|threat)*>
        <!ELEMENT host (ip|start|end|detail)*>
        <!ELEMENT threat (#PCDATA)>
        <!ELEMENT results (result)*>
        <!ATTLIST results
                start CDATA #REQUIRED
                max CDATA #REQUIRED>
        <!ELEMENT result (subnet|host|port|nvt|threat|description|original_threat|notes|overrides|detection|details)*>
        <!ATTLIST result
                id CDATA #REQUIRED>
        <!ELEMENT subnet (#PCDATA)>
        <!ELEMENT nvt (name|family|cvss_base|risk_factor|cve|bid|tags|cert|xref)*>
        <!ATTLIST nvt
                oid CDATA #REQUIRED>
        <!ELEMENT family (#PCDATA)>
        <!ELEMENT cvss_base (#PCDATA)>
        <!ELEMENT risk_factor (#PCDATA)>
        <!ELEMENT cve (#PCDATA)>
        <!ELEMENT bid (#PCDATA)>
        <!ELEMENT tags (#PCDATA)>
        <!ELEMENT cert (cert_ref)*>
        <!ELEMENT xref (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT original_threat (#PCDATA)>
        <!ELEMENT detection (result)*>
        <!ELEMENT details (detail)*>
        <!ELEMENT detail (name|value|source)*>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT cert_ref (#PCDATA)>
        <!ATTLIST cert_ref
                id CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT result_count (full|filtered|debug|hole|info|log|warning|false_positive)*>
        <!ELEMENT full (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        <!ELEMENT debug (full|filtered)*>
        <!ELEMENT hole (full|filtered)*>
        <!ELEMENT info (full|filtered)*>
        <!ELEMENT log (full|filtered)*>
        <!ELEMENT warning (full|filtered)*>
        <!ELEMENT false_positive (full|filtered)*>
        <!ELEMENT ip (#PCDATA)>
        <!ELEMENT start (#PCDATA)>
        <!ELEMENT end (#PCDATA)>
        <!ELEMENT source (type|name|description)*>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT host_start (host)*>
        <!ELEMENT host_end (host)*>
        <!ELEMENT scan_end (#PCDATA)>
        ]>
<report extension="xml" id="23327e93-b82d-4c41-9a26-ce99f15bbc63" type="scan" content_type="text/xml" format_id="a994b278-1f62-11e1-96ac-406186ea4fc5"><report id="23327e93-b82d-4c41-9a26-ce99f15bbc63"><report_format></report_format><sort><field>type<order>descending</order></field></sort><filters id="0">hmlgf<term>sort-reverse=type result_hosts_only=1 min_cvss_base= levels=hmlgf autofp=0 show_closed_cves=0 notes=1 overrides=1 first=1 rows=148 delta_states=gn</term><phrase></phrase><autofp>0</autofp><show_closed_cves>0</show_closed_cves><notes>1</notes><overrides>1</overrides><apply_overrides>1</apply_overrides><result_hosts_only>1</result_hosts_only><min_cvss_base></min_cvss_base><filter>High</filter><filter>Medium</filter><filter>Low</filter><filter>Log</filter><filter>False Positive</filter></filters><scan_run_status>Done</scan_run_status><task id="299fadd1-2045-4274-a255-2cb772f4d6dd"><name>Immediate scan of IP 10.211.55.35</name><comment></comment><target id="b92cc592-e832-4d20-a1a6-77afd42d7f95"><trash>0</trash></target></task><scan_start>2014-04-13T02:13:34Z</scan_start><ports start="1" max="148"><port>clm_pts (6200/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>distcc (3632/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>ftp (21/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>http (80/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>ingreslock (1524/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>ircd (6667/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>mysql (3306/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>nfs (2049/udp)<host>10.211.55.35</host><threat>High</threat></port><port>postgresql (5432/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>scientia-ssdb (2121/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>ssh (22/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>x11 (6000/tcp)<host>10.211.55.35</host><threat>High</threat></port><port>exec (512/tcp)<host>10.211.55.35</host><threat>Medium</threat></port><port>general/tcp<host>10.211.55.35</host><threat>Medium</threat></port><port>microsoft-ds (445/tcp)<host>10.211.55.35</host><threat>Medium</threat></port><port>shell (514/tcp)<host>10.211.55.35</host><threat>Medium</threat></port><port>smtp (25/tcp)<host>10.211.55.35</host><threat>Medium</threat></port><port>domain (53/tcp)<host>10.211.55.35</host><threat>Low</threat></port><port>msgsrvr (8787/tcp)<host>10.211.55.35</host><threat>Low</threat></port><port>telnet (23/tcp)<host>10.211.55.35</host><threat>Low</threat></port><port>tftp (69/udp)<host>10.211.55.35</host><threat>Low</threat></port><port>vnc (5900/tcp)<host>10.211.55.35</host><threat>Low</threat></port><port>ajp13 (8009/tcp)<host>10.211.55.35</host><threat>Log</threat></port><port>domain (53/udp)<host>10.211.55.35</host><threat>Log</threat></port><port>general/CPE-T<host>10.211.55.35</host><threat>Log</threat></port><port>general/HOST-T<host>10.211.55.35</host><threat>Log</threat></port><port>general/SMBClient<host>10.211.55.35</host><threat>Log</threat></port><port>general/icmp<host>10.211.55.35</host><threat>Log</threat></port><port>login (513/tcp)<host>10.211.55.35</host><threat>Log</threat></port><port>netbios-ns (137/udp)<host>10.211.55.35</host><threat>Log</threat></port><port>netbios-ssn (139/tcp)<host>10.211.55.35</host><threat>Log</threat></port><port>nfs (2049/tcp)<host>10.211.55.35</host><threat>Log</threat></port><port>rmiregistry (1099/tcp)<host>10.211.55.35</host><threat>Log</threat></port><port>sunrpc (111/tcp)<host>10.211.55.35</host><threat>Log</threat></port></ports><results start="1" max="148"><result id="685ab07e-9ac8-488e-b7b2-f3f97bd37505"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>clm_pts (6200/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.103185"><name>vsftpd Compromised Source Packages Backdoor Vulnerability</name><family>Gain a shell remotely</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>NOCVE</cve><bid>48539</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 vsftpd is prone to a backdoor vulnerability.

Attackers can exploit this issue to execute arbitrary commands in the
context of the application. Successful attacks will compromise the
affected application.

The vsftpd 2.3.4 source package is affected.
 Solution:
 The repaired package can be downloaded from
https://security.appspot.com/vsftpd.html. Please validate the package
with its signature.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="eb1c0032-adc5-43f6-a2db-9e8431ef5464"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>distcc (3632/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.103553"><name>distcc Remote Code Execution Vulnerability</name><family>General</family><cvss_base>9.3</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2004-2687</cve><bid>NOBID</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 distcc 2.x, as used in XCode 1.5 and others, when not configured to restrict
access to the server port, allows remote attackers to execute arbitrary
commands via compilation jobs, which are executed by the server without
authorization checks.
 Solution:
 Vendor updates are available. Please see the references for more
information.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="20b3acf3-41d8-47e0-b7f6-637d693e320f"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>ftp (21/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.103185"><name>vsftpd Compromised Source Packages Backdoor Vulnerability</name><family>Gain a shell remotely</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>NOCVE</cve><bid>48539</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 vsftpd is prone to a backdoor vulnerability.

Attackers can exploit this issue to execute arbitrary commands in the
context of the application. Successful attacks will compromise the
affected application.

The vsftpd 2.3.4 source package is affected.
 Solution:
 The repaired package can be downloaded from
https://security.appspot.com/vsftpd.html. Please validate the package
with its signature.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="2ddf03b3-26ef-4cfb-be56-9a0d6597d893"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>ftp (21/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.900507"><name>ProFTPD Server SQL Injection Vulnerability</name><family>FTP</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2009-0542, CVE-2009-0543</cve><bid>33722</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>

  Summary:
  This host is running ProFTPD Server and is prone to remote
  SQL Injection vulnerability.

  Vulnerability Insight:
  This flaw occurs because the server performs improper input sanitising,
  - when a %(percent) character is passed in the username, a single quote
    (&apos;) gets introduced during variable substitution by mod_sql and this
    eventually allows for an SQL injection during login.
  - when NLS support is enabled, a flaw in variable substition feature in
    mod_sql_mysql and mod_sql_postgres may allow an attacker to bypass
    SQL injection protection mechanisms via invalid, encoded multibyte
    characters.

  Impact:
  Successful exploitation will allow remote attackers to execute arbitrary
  SQL commands, thus gaining access to random user accounts.

  Affected Software/OS:
  ProFTPD Server version 1.3.1 through 1.3.2rc2

  Solution:
  Upgrade to the latest version 1.3.2rc3,
  http://www.proftpd.org/
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="7a2effb6-23eb-420f-85b9-c1b8e1c93d54"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>ftp (21/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.100316"><name>ProFTPD mod_tls Module NULL Character CA SSL Certificate Validation Security Bypass Vulnerability</name><family>FTP</family><cvss_base>5.8</cvss_base><risk_factor>High</risk_factor><cve>CVE-2009-3639</cve><bid>36804</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:N/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 ProFTPD is prone to a security-bypass vulnerability because the
application fails to properly validate the domain name in a signed CA
certificate, allowing attackers to substitute malicious SSL
certificates for trusted ones.

Successful exploits allows attackers to perform man-in-the-
middle attacks or impersonate trusted servers, which will aid in
further attacks.

Versions prior to ProFTPD 1.3.2b and 1.3.3 to 1.3.3.rc1 are vulnerable.
 Solution:
 Updates are available. Please see the references for details.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="1167905e-d62d-42a1-b0e4-0a2044bd4032"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110172"><name>PHP version smaller than 5.2.7</name><family>Web application abuses</family><cvss_base>10.0</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2008-2371, CVE-2008-2665, CVE-2008-2666, CVE-2008-2829, CVE-2008-3658, CVE-2008-3659, CVE-2008-3660, CVE-2008-5557, CVE-2008-5624, CVE-2008-5625, CVE-2008-5658</cve><bid>29796, 29797, 29829, 30087, 30649, 31612, 32383, 32625, 32688, 32948</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.7 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.7 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="29ba8c4f-fa13-4a25-9ff5-3a26feee44e3"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110183"><name>PHP version smaller than 5.2.6</name><family>Web application abuses</family><cvss_base>10.0</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2007-4850, CVE-2007-6039, CVE-2008-0599, CVE-2008-1384, CVE-2008-2050, CVE-2008-2051</cve><bid>27413, 28392, 29009</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.6 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.6 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="136a694e-25b0-4ef0-8c36-8ef29d20fe27"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110171"><name>PHP version smaller than 5.2.14</name><family>Web application abuses</family><cvss_base>9.3</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2007-1581, CVE-2010-0397, CVE-2010-1860, CVE-2010-1862, CVE-2010-1864, CVE-2010-2097, CVE-2010-2100, CVE-2010-2101, CVE-2010-2190, CVE-2010-2191, CVE-2010-2225, CVE-2010-2484, CVE-2010-2531, CVE-2010-3065</cve><bid>38708, 40948, 41991</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.14 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.14 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="88309fa6-7cc0-462a-a837-3ece58c176ef"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110179"><name>PHP version smaller than 5.2.5</name><family>Web application abuses</family><cvss_base>9.3</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2007-3996, CVE-2007-4782, CVE-2007-4783, CVE-2007-4784, CVE-2007-4825, CVE-2007-4840, CVE-2007-4887, CVE-2007-4889, CVE-2007-5447, CVE-2007-5653, CVE-2007-5898, CVE-2007-5899, CVE-2007-5900, CVE-2008-2107, CVE-2008-2108, CVE-2008-4107</cve><bid>26403</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.5 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.5 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="009b28d1-c33b-4eb2-b0da-d1d506d95db4"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110182"><name>PHP version smaller than 5.3.3</name><family>Web application abuses</family><cvss_base>9.3</cvss_base><risk_factor>Critical</risk_factor><cve>CVE-2007-1581, CVE-2010-0397, CVE-2010-1860, CVE-2010-1862, CVE-2010-1864, CVE-2010-1917, CVE-2010-2097, CVE-2010-2100, CVE-2010-2101, CVE-2010-2190, CVE-2010-2191, CVE-2010-2225, CVE-2010-2484, CVE-2010-2531, CVE-2010-3062, CVE-2010-3063, CVE-2010-3064, CVE-2010-3065</cve><bid>38708, 40461, 40948, 41991</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.3.3 suffers vulnerability.
  Solution:
  Update PHP to version 5.3.3 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="34a491fd-a184-4d67-a7d3-0d7ce3a2b93a"><detection><result id="9629c9b4-5de2-45ee-9f45-3ce3a6577c27"><details><detail><name>product</name><value>cpe:/a:tikiwiki:tikiwiki:1.9.5</value></detail><detail><name>location</name><value>/tikiwiki</value></detail><detail><name>source_oid</name><value>1.3.6.1.4.1.25623.1.0.901001</value></detail><detail><name>source_name</name><value>TikiWiki Version Detection</value></detail></details></result></detection><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.100537"><name>TikiWiki Versions Prior to 4.2 Multiple Unspecified Vulnerabilities</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2010-1135, CVE-2010-1134, CVE-2010-1133, CVE-2010-1136</cve><bid>38608</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 TikiWiki is prone to multiple unspecified vulnerabilities, including:

- An unspecified SQL-injection vulnerability
- An unspecified authentication-bypass vulnerability
- An unspecified vulnerability

Exploiting these issues could allow an attacker to compromise the
application, access or modify data, exploit latent vulnerabilities in
the underlying database, and gain unauthorized access to the affected
application. Other attacks are also possible.

Versions prior to TikiWiki 4.2 are vulnerable.
 Solution:
 The vendor has released an advisory and fixes. Please see the
references for details.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="98a04741-d7aa-43bf-bd36-b981c813b7e1"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.103482"><name>PHP-CGI-based setups vulnerability when parsing query string parameters from php files.</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2012-1823, CVE-2012-2311, CVE-2012-2336, CVE-2012-2335</cve><bid>53388</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert><cert_ref id="DFN-CERT-2012-1276" type="DFN-CERT"></cert_ref></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 When PHP is used in a CGI-based setup (such as Apache&apos;s mod_cgid), the
php-cgi receives a processed query string parameter as command line
arguments which allows command-line switches, such as -s, -d or -c to be
passed to the php-cgi binary, which can be exploited to disclose source
code and obtain arbitrary code execution.

An example of the -s command, allowing an attacker to view the source code
of index.php is below:

http://localhost/index.php?-s
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="79d89572-346e-4ebb-a987-6068199afbd9"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110176"><name>PHP version smaller than 5.2.11</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2009-3291, CVE-2009-3292, CVE-2009-3293, CVE-2009-3294, CVE-2009-4018, CVE-2009-5016</cve><bid>36449, 44889</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.11 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.11 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="cb206447-ff55-4efc-a1f0-5cdee26617bd"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110178"><name>PHP version smaller than 5.3.1</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2009-3557, CVE-2009-3559, CVE-2009-4017, CVE-2009-4018, CVE-2010-1128</cve><bid>36554, 36555, 37079, 37138</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.3.1 suffers vulnerability.
  Solution:
  Update PHP to version 5.3.1 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="27e0f0ba-8f2f-4614-baab-f351aef412a1"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110180"><name>PHP version smaller than 5.2.8</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2008-5814, CVE-2008-5844</cve><bid>32673</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.2.8 suffers vulnerability.
  Solution:
  Update PHP to version 5.2.8 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="52c5d8a5-7283-4e6c-8a5a-9bdb5d3b37c7"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.11229"><name>phpinfo.php</name><family>Web application abuses</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>NOCVE</cve><bid>NOBID</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
The following files are calling the function phpinfo() which
disclose potentially sensitive information to the remote attacker : 
/phpinfo.php


Solution: Delete them or restrict access to them
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="0491f7ab-04e8-4727-b8e7-dfa1e68f56b9"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.110181"><name>PHP version smaller than 5.3.4</name><family>Web application abuses</family><cvss_base>6.8</cvss_base><risk_factor>High</risk_factor><cve>CVE-2006-7243, CVE-2010-2094, CVE-2010-2950, CVE-2010-3436, CVE-2010-3709, CVE-2010-3710, CVE-2010-3870, CVE-2010-4150, CVE-2010-4156, CVE-2010-4409, CVE-2010-4697, CVE-2010-4698, CVE-2010-4699, CVE-2010-4700, CVE-2011-0753, CVE-2011-0754, CVE-2011-0755</cve><bid>40173, 43926, 44605, 44718, 44723, 44951, 44980, 45119, 45335, 45338, 45339, 45952, 45954, 46056, 46168</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
  Summary:
  PHP version smaller than 5.3.4 suffers vulnerability.
  Solution:
  Update PHP to version 5.3.4 or later.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="32ea2228-673a-4ec0-ac0c-c383b84fc1a0"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>http (80/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.11213"><name>http TRACE XSS attack</name><family>Web application abuses</family><cvss_base>5.8</cvss_base><risk_factor>High</risk_factor><cve>CVE-2004-2320, CVE-2003-1567</cve><bid>9506, 9561, 11604</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:P/I:P/A:N</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 Debugging functions are enabled on the remote HTTP server.

Description :

The remote webserver supports the TRACE and/or TRACK methods. TRACE and TRACK
are HTTP methods which are used to debug web server connections.   

It has been shown that servers supporting this method are subject to
cross-site-scripting attacks, dubbed XST for Cross-Site-Tracing, when
used in conjunction with various weaknesses in browsers. 

An attacker may use this flaw to trick your legitimate web users to give
him their credentials.
 Solution:
 Disable these methods.

Plugin output :


Solution: 
Add the following lines for each virtual host in your configuration file :

    RewriteEngine on
    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
    RewriteRule .* - [F]

See also http://httpd.apache.org/docs/current/de/mod/core.html#traceenable    


</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="fd7d22c5-cd1e-486b-afbe-a43f35f42e8f"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>ingreslock (1524/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.103549"><name>Possible Backdoor: Ingreslock</name><family>Gain a shell remotely</family><cvss_base>10.0</cvss_base><risk_factor>Critical</risk_factor><cve>NOCVE</cve><bid>NOBID</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 A backdoor is installed on the remote host

Attackers can exploit this issue to execute arbitrary commands in the
context of the application. Successful attacks will compromise the
affected isystem.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="26364dff-d68e-478c-828f-92380da4b4f8"><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>ircd (6667/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.80111"><name>Check for Backdoor in unrealircd</name><family>Gain a shell remotely</family><cvss_base>7.5</cvss_base><risk_factor>High</risk_factor><cve>CVE-2010-2075</cve><bid>40820</bid><tags>cvss_base_vector=AV:N/AC:L/Au:N/C:P/I:P/A:P</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 Detection of backdoor in unrealircd.
 Vulnerability Insight:
 Remote attackers can exploit this issue to execute arbitrary system
commands within the context of the affected application.

The issue affects Unreal 3.2.8.1 for Linux. Reportedly package
Unreal3.2.8.1.tar.gz downloaded in November 2009 and later is
affected. The MD5 sum of the affected file is
752e46f2d873c1679fa99de3f52a274d. Files with MD5 sum of
7b741e94e867c0a7370553fd01506c66 are not affected.
 Solution:
 Install latest version of unrealircd and check signatures of software
you&apos;re installing.
</description><original_threat>High</original_threat><notes></notes><overrides></overrides></result><result id="5bb64b44-bf56-4bf1-89b6-027718c29a39"><detection><result id="0c765983-0524-462a-8520-41f70dd7230b"><details><detail><name>product</name><value>cpe:/a:mysql:mysql:5.0.51a</value></detail><detail><name>location</name><value>3306/tcp</value></detail><detail><name>source_oid</name><value>1.3.6.1.4.1.25623.1.0.100152</value></detail><detail><name>source_name</name><value>MySQL/MariaDB Detection</value></detail></details></result></detection><subnet>10.211.55.35</subnet><host>10.211.55.35</host><port>mysql (3306/tcp)</port><nvt oid="1.3.6.1.4.1.25623.1.0.100271"><name>MySQL 5.x Unspecified Buffer Overflow Vulnerability</name><family>Databases</family><cvss_base>9.3</cvss_base><risk_factor>Critical</risk_factor><cve>NOCVE</cve><bid>36242</bid><tags>cvss_base_vector=AV:N/AC:M/Au:N/C:C/I:C/A:C</tags><cert></cert><xref>NOXREF</xref></nvt><threat>High</threat><description>
 Summary:
 MySQL is prone to a buffer-overflow vulnerability because if fails to
perform adequate boundary checks on user-supplied data.

An attacker can leverage this issue to execute arbitrary code within
the context of the vulnerable application. Failed exploit attempts
will result in a denial-of-service condition.

This issue affects MySQL 5.x; other versions may also be vulnerable.